name: drassy_api
version: 0.0.1
description: Drassy Api package
homepage: homepage

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dio: ^4.0.6
  built_value: ^8.1.4
  built_collection: ^5.1.1

dev_dependencies:
  built_value_generator: ^8.1.4
  build_runner: any
  test: ^1.20.2
